version: '2'
services:
  traefik:
     image: traefik
     restart: always
     ports:
       - 80:80
       - 443:443
       - 8080:8080
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - ./traefik.toml:/traefik.toml
       - ./acme.json:/acme.json
     container_name: traefik
     networks:
       - reverse_proxy
networks:
  reverse_proxy:
    external: true
