debug = true
checkNewVersion = true
logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
    regex = "^http://(www\\.)?(xxx\\.com)/(.*)"
    replacement="https://www.$2/$3"
    permanent = true # redirect permanently
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
   [entryPoints.foo.auth]
     [entryPoints.foo.auth.basic]
       users = [
         "admin:$apr1$ulqJgMt2$WIWb4d6Zv.cqkE.IUbQEs0",
       ]

[api]
entrypoint="foo"

#[web]
# Port for the status page
#address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "xxxx.com" # <-- change this domain
watch = true
exposedbydefault = false

[acme]
email = "J.sichaib@xxx.com" # <-- change this email
storage = "acme.json"
entryPoint = "https"
[acme.httpChallenge]
  entryPoint = "http"
OnHostRule = true
[[acme.domains]]
  main = "www.xxxx.com"
